
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2006-12-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
//using System.Text;
//using System.Collections;
//using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
//using System.Web.Services;
//using System.Web.Services.Description;
//using System.Web.Services.Protocols;
using SAP.Connector;

namespace RFCProxyBuilder
{

  /// <summary>
  /// RFC: Table Fields with UNICODE Information
  /// </summary>
  [RfcStructure(AbapName ="RFC_FLDS_U" , Length = 96, Length2 = 156)]
  [Serializable]
  public class RFC_FLDS_U : SAPStructure
  {
   

    /// <summary>
    /// Table Name
    /// </summary>
 
    [RfcField(AbapName = "TABNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 0, Offset2 = 0)]
    [XmlElement("TABNAME", Form=XmlSchemaForm.Unqualified)]
    public string TABNAME
    { 
       get
       {
          return _TABNAME;
       }
       set
       {
          _TABNAME = value;
       }
    }
    private string _TABNAME;


    /// <summary>
    /// Field Name
    /// </summary>
 
    [RfcField(AbapName = "FIELDNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 30, Offset2 = 60)]
    [XmlElement("FIELDNAME", Form=XmlSchemaForm.Unqualified)]
    public string FIELDNAME
    { 
       get
       {
          return _FIELDNAME;
       }
       set
       {
          _FIELDNAME = value;
       }
    }
    private string _FIELDNAME;


    /// <summary>
    /// Position of field in structure (from 1)
    /// </summary>
 
    [RfcField(AbapName = "POSITION", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 60, Offset2 = 120)]
    [XmlElement("POSITION", Form=XmlSchemaForm.Unqualified)]
    public int POSITION
    { 
       get
       {
          return _POSITION;
       }
       set
       {
          _POSITION = value;
       }
    }
    private int _POSITION;


    /// <summary>
    /// ABAP/4 data type
    /// </summary>
 
    [RfcField(AbapName = "EXID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 64, Offset2 = 124)]
    [XmlElement("EXID", Form=XmlSchemaForm.Unqualified)]
    public string EXID
    { 
       get
       {
          return _EXID;
       }
       set
       {
          _EXID = value;
       }
    }
    private string _EXID;


    /// <summary>
    /// Number of decimal places
    /// </summary>
 
    [RfcField(AbapName = "DECIMALS", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 68, Offset2 = 128)]
    [XmlElement("DECIMALS", Form=XmlSchemaForm.Unqualified)]
    public int DECIMALS
    { 
       get
       {
          return _DECIMALS;
       }
       set
       {
          _DECIMALS = value;
       }
    }
    private int _DECIMALS;


    /// <summary>
    /// Field Offset 1 Byte per Character Systems
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_B1", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 72, Offset2 = 132)]
    [XmlElement("OFFSET_B1", Form=XmlSchemaForm.Unqualified)]
    public int OFFSET_B1
    { 
       get
       {
          return _OFFSET_B1;
       }
       set
       {
          _OFFSET_B1 = value;
       }
    }
    private int _OFFSET_B1;


    /// <summary>
    /// Internal Field Length in 1 byte per Character Systems
    /// </summary>
 
    [RfcField(AbapName = "LENGTH_B1", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 76, Offset2 = 136)]
    [XmlElement("LENGTH_B1", Form=XmlSchemaForm.Unqualified)]
    public int LENGTH_B1
    { 
       get
       {
          return _LENGTH_B1;
       }
       set
       {
          _LENGTH_B1 = value;
       }
    }
    private int _LENGTH_B1;


    /// <summary>
    /// Field Offset in 2 Bytes per Character Systems
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_B2", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 80, Offset2 = 140)]
    [XmlElement("OFFSET_B2", Form=XmlSchemaForm.Unqualified)]
    public int OFFSET_B2
    { 
       get
       {
          return _OFFSET_B2;
       }
       set
       {
          _OFFSET_B2 = value;
       }
    }
    private int _OFFSET_B2;


    /// <summary>
    /// Internal Field Length in 2 bytes per Character Systems
    /// </summary>
 
    [RfcField(AbapName = "LENGTH_B2", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 84, Offset2 = 144)]
    [XmlElement("LENGTH_B2", Form=XmlSchemaForm.Unqualified)]
    public int LENGTH_B2
    { 
       get
       {
          return _LENGTH_B2;
       }
       set
       {
          _LENGTH_B2 = value;
       }
    }
    private int _LENGTH_B2;


    /// <summary>
    /// Field Offset in 4 bytes per Character Systems
    /// </summary>
 
    [RfcField(AbapName = "OFFSET_B4", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 88, Offset2 = 148)]
    [XmlElement("OFFSET_B4", Form=XmlSchemaForm.Unqualified)]
    public int OFFSET_B4
    { 
       get
       {
          return _OFFSET_B4;
       }
       set
       {
          _OFFSET_B4 = value;
       }
    }
    private int _OFFSET_B4;


    /// <summary>
    /// Internal Field Length in 4 bytes per Character Systems
    /// </summary>
 
    [RfcField(AbapName = "LENGTH_B4", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 92, Offset2 = 152)]
    [XmlElement("LENGTH_B4", Form=XmlSchemaForm.Unqualified)]
    public int LENGTH_B4
    { 
       get
       {
          return _LENGTH_B4;
       }
       set
       {
          _LENGTH_B4 = value;
       }
    }
    private int _LENGTH_B4;

  }

}
