
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2006-12-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
//using System.Text;
//using System.Collections;
//using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
//using System.Web.Services;
//using System.Web.Services.Description;
//using System.Web.Services.Protocols;
using SAP.Connector;

namespace RFCProxyBuilder
{

  /// <summary>
  /// RFC: Attributes of function parameters
  /// </summary>
  [RfcStructure(AbapName ="RFC_FUNINT" , Length = 212, Length2 = 404)]
  [Serializable]
  public class RFC_FUNINT : SAPStructure
  {
   

    /// <summary>
    /// Parameter type
    /// </summary>
 
    [RfcField(AbapName = "PARAMCLASS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("PARAMCLASS", Form=XmlSchemaForm.Unqualified)]
    public string PARAMCLASS
    { 
       get
       {
          return _PARAMCLASS;
       }
       set
       {
          _PARAMCLASS = value;
       }
    }
    private string _PARAMCLASS;


    /// <summary>
    /// Parameter name
    /// </summary>
 
    [RfcField(AbapName = "PARAMETER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 1, Offset2 = 2)]
    [XmlElement("PARAMETER", Form=XmlSchemaForm.Unqualified)]
    public string PARAMETER
    { 
       get
       {
          return _PARAMETER;
       }
       set
       {
          _PARAMETER = value;
       }
    }
    private string _PARAMETER;


    /// <summary>
    /// Table Name
    /// </summary>
 
    [RfcField(AbapName = "TABNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 31, Offset2 = 62)]
    [XmlElement("TABNAME", Form=XmlSchemaForm.Unqualified)]
    public string TABNAME
    { 
       get
       {
          return _TABNAME;
       }
       set
       {
          _TABNAME = value;
       }
    }
    private string _TABNAME;


    /// <summary>
    /// Field Name
    /// </summary>
 
    [RfcField(AbapName = "FIELDNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 61, Offset2 = 122)]
    [XmlElement("FIELDNAME", Form=XmlSchemaForm.Unqualified)]
    public string FIELDNAME
    { 
       get
       {
          return _FIELDNAME;
       }
       set
       {
          _FIELDNAME = value;
       }
    }
    private string _FIELDNAME;


    /// <summary>
    /// ABAP Data Type
    /// </summary>
 
    [RfcField(AbapName = "EXID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 91, Offset2 = 182)]
    [XmlElement("EXID", Form=XmlSchemaForm.Unqualified)]
    public string EXID
    { 
       get
       {
          return _EXID;
       }
       set
       {
          _EXID = value;
       }
    }
    private string _EXID;


    /// <summary>
    /// Position of field in structure (from 1)
    /// </summary>
 
    [RfcField(AbapName = "POSITION", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 92, Offset2 = 184)]
    [XmlElement("POSITION", Form=XmlSchemaForm.Unqualified)]
    public int POSITION
    { 
       get
       {
          return _POSITION;
       }
       set
       {
          _POSITION = value;
       }
    }
    private int _POSITION;


    /// <summary>
    /// Field offset from beginning of structure (from 0)
    /// </summary>
 
    [RfcField(AbapName = "OFFSET", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 96, Offset2 = 188)]
    [XmlElement("OFFSET", Form=XmlSchemaForm.Unqualified)]
    public int OFFSET
    { 
       get
       {
          return _OFFSET;
       }
       set
       {
          _OFFSET = value;
       }
    }
    private int _OFFSET;


    /// <summary>
    /// Internal length of field
    /// </summary>
 
    [RfcField(AbapName = "INTLENGTH", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 100, Offset2 = 192)]
    [XmlElement("INTLENGTH", Form=XmlSchemaForm.Unqualified)]
    public int INTLENGTH
    { 
       get
       {
          return _INTLENGTH;
       }
       set
       {
          _INTLENGTH = value;
       }
    }
    private int _INTLENGTH;


    /// <summary>
    /// Number of decimal places
    /// </summary>
 
    [RfcField(AbapName = "DECIMALS", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 104, Offset2 = 196)]
    [XmlElement("DECIMALS", Form=XmlSchemaForm.Unqualified)]
    public int DECIMALS
    { 
       get
       {
          return _DECIMALS;
       }
       set
       {
          _DECIMALS = value;
       }
    }
    private int _DECIMALS;


    /// <summary>
    /// Default value for import parameter
    /// </summary>
 
    [RfcField(AbapName = "DEFAULT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 21, Length2 = 42, Offset = 108, Offset2 = 200)]
    [XmlElement("DEFAULT", Form=XmlSchemaForm.Unqualified)]
    public string DEFAULT
    { 
       get
       {
          return _DEFAULT;
       }
       set
       {
          _DEFAULT = value;
       }
    }
    private string _DEFAULT;


    /// <summary>
    /// Short text
    /// </summary>
 
    [RfcField(AbapName = "PARAMTEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 79, Length2 = 158, Offset = 129, Offset2 = 242)]
    [XmlElement("PARAMTEXT", Form=XmlSchemaForm.Unqualified)]
    public string PARAMTEXT
    { 
       get
       {
          return _PARAMTEXT;
       }
       set
       {
          _PARAMTEXT = value;
       }
    }
    private string _PARAMTEXT;


    /// <summary>
    /// Optional parameters
    /// </summary>
 
    [RfcField(AbapName = "OPTIONAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 208, Offset2 = 400)]
    [XmlElement("OPTIONAL", Form=XmlSchemaForm.Unqualified)]
    public string OPTIONAL
    { 
       get
       {
          return _OPTIONAL;
       }
       set
       {
          _OPTIONAL = value;
       }
    }
    private string _OPTIONAL;

  }

}
