
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2006-12-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
//using System.Text;
//using System.Collections;
//using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
//using System.Web.Services;
//using System.Web.Services.Description;
//using System.Web.Services.Protocols;
using SAP.Connector;

namespace RFCProxyBuilder
{

  /// <summary>
  /// Remote function module short text
  /// </summary>
  [RfcStructure(AbapName ="RFCFUNC" , Length = 163, Length2 = 326)]
  [Serializable]
  public class RFCFUNC : SAPStructure
  {
   

    /// <summary>
    /// Name of Function Module
    /// </summary>
 
    [RfcField(AbapName = "FUNCNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 0, Offset2 = 0)]
    [XmlElement("FUNCNAME", Form=XmlSchemaForm.Unqualified)]
    public string FUNCNAME
    { 
       get
       {
          return _FUNCNAME;
       }
       set
       {
          _FUNCNAME = value;
       }
    }
    private string _FUNCNAME;


    /// <summary>
    /// Function group, to which the function module belongs
    /// </summary>
 
    [RfcField(AbapName = "GROUPNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 26, Length2 = 52, Offset = 30, Offset2 = 60)]
    [XmlElement("GROUPNAME", Form=XmlSchemaForm.Unqualified)]
    public string GROUPNAME
    { 
       get
       {
          return _GROUPNAME;
       }
       set
       {
          _GROUPNAME = value;
       }
    }
    private string _GROUPNAME;


    /// <summary>
    /// Application to which function module is assigned
    /// </summary>
 
    [RfcField(AbapName = "APPL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 56, Offset2 = 112)]
    [XmlElement("APPL", Form=XmlSchemaForm.Unqualified)]
    public string APPL
    { 
       get
       {
          return _APPL;
       }
       set
       {
          _APPL = value;
       }
    }
    private string _APPL;


    /// <summary>
    /// Remote host (CPIC)
    /// </summary>
 
    [RfcField(AbapName = "HOST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 32, Length2 = 64, Offset = 57, Offset2 = 114)]
    [XmlElement("HOST", Form=XmlSchemaForm.Unqualified)]
    public string HOST
    { 
       get
       {
          return _HOST;
       }
       set
       {
          _HOST = value;
       }
    }
    private string _HOST;


    /// <summary>
    /// Short text for function module
    /// </summary>
 
    [RfcField(AbapName = "STEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 74, Length2 = 148, Offset = 89, Offset2 = 178)]
    [XmlElement("STEXT", Form=XmlSchemaForm.Unqualified)]
    public string STEXT
    { 
       get
       {
          return _STEXT;
       }
       set
       {
          _STEXT = value;
       }
    }
    private string _STEXT;

  }

}
