
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2006-12-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Xml.Schema;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;
using SAP.Connector.Rfc;

namespace RFCProxyBuilder
{

    /// <summary>
    /// Client SAP proxy class
    /// </summary>
    [WebServiceBinding(Name = "dummy.Binding", Namespace = "urn:sap-com:document:sap:rfc:functions")]
    [Serializable]
    public class SAPProxy : SAPClient
    {
        /// <summary>
        /// Initializes a new SAPProxy.
        /// </summary>
        public SAPProxy() { }

        /// <summary>
        /// Initializes a new SAPProxy with a new connection based on the specified connection string.
        /// </summary>
        /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
        public SAPProxy(string connectionString) : base(connectionString) { }

        /// <summary>
        /// Initializes a new SAPProxy instance and adds it to the given container.
        /// This allows automated connection mananged by VS component designer:
        /// If container is disposed, it will also dispose this SAPClient instance,
        /// which will dispose a contained connection if needed.
        /// </summary>
        /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
        public SAPProxy(System.ComponentModel.IContainer container) : base(container) { }

        /// <summary>
        /// Exception constant for ABAP-Exception NOTHING_SPECIFIED
        /// </summary>
        public const string NOTHING_SPECIFIED = "NOTHING_SPECIFIED";

        /// <summary>
        /// Exception constant for ABAP-Exception NO_FUNCTION_FOUND
        /// </summary>
        public const string NO_FUNCTION_FOUND = "NO_FUNCTION_FOUND";

        /// <summary>
        /// Exception constant for ABAP-Exception FU_NOT_FOUND
        /// </summary>
        public const string FU_NOT_FOUND = "FU_NOT_FOUND";

        /// <summary>
        /// Exception constant for ABAP-Exception NAMETAB_FAULT
        /// </summary>
        public const string NAMETAB_FAULT = "NAMETAB_FAULT";

        /// <summary>
        /// Exception constant for ABAP-Exception TABLE_NOT_ACTIVE
        /// </summary>
        public const string TABLE_NOT_ACTIVE = "TABLE_NOT_ACTIVE";

        /// <summary>
        /// Exception constant for ABAP-Exception CANNOT_GENERATE1
        /// </summary>
        public const string CANNOT_GENERATE1 = "CANNOT_GENERATE1";

        /// <summary>
        /// Exception constant for ABAP-Exception CANNOT_GENERATE2
        /// </summary>
        public const string CANNOT_GENERATE2 = "CANNOT_GENERATE2";

        /// <summary>
        /// Exception constant for ABAP-Exception CANNOT_GENERATE4
        /// </summary>
        public const string CANNOT_GENERATE4 = "CANNOT_GENERATE4";

        /// <summary>
        /// Exception constant for ABAP-Exception UNSUPPORTED_TYPE
        /// </summary>
        public const string UNSUPPORTED_TYPE = "UNSUPPORTED_TYPE";

        /// <summary>
        /// Remote Function Module RFC_FUNCTION_SEARCH.  
        /// 
        /// </summary>
        /// <param name="FUNCNAME">Name of function module</param>
        /// <param name="GROUPNAME">Name of group</param>
        /// <param name="LANGUAGE">Language for parameter texts</param>
        /// <param name="FUNCTIONS">Parameter of function list</param> 
        /// <exception cref="NOTHING_SPECIFIED"/> 
        /// <exception cref="NO_FUNCTION_FOUND"/>
        [RfcMethod(AbapName = "RFC_FUNCTION_SEARCH")]
        [SoapDocumentMethodAttribute("http://tempuri.org/RFC_FUNCTION_SEARCH",
             RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
             RequestElementName = "RFC_FUNCTION_SEARCH",
             ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
             ResponseElementName = "RFC_FUNCTION_SEARCH.Response")]
        public virtual void RFC_FUNCTION_SEARCH(

            [RfcParameter(AbapName = "FUNCNAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
            [XmlElement("FUNCNAME", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string FUNCNAME,
            [RfcParameter(AbapName = "GROUPNAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 26, Length2 = 52)]
            [XmlElement("GROUPNAME", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string GROUPNAME,
            [RfcParameter(AbapName = "LANGUAGE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
            [XmlElement("LANGUAGE", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string LANGUAGE,
            [RfcParameter(AbapName = "FUNCTIONS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
            [XmlArray("FUNCTIONS", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            ref RFCFUNCTable FUNCTIONS)
        {

            try
            {
                object[] results = null;
                results = this.SAPInvoke("RFC_FUNCTION_SEARCH", new object[] { FUNCNAME, GROUPNAME, LANGUAGE, FUNCTIONS });
                FUNCTIONS = (RFCFUNCTable)results[0];

            }
            catch (SoapException rx)
            {
                throw rx;
            }
            catch (Exception ex)
            {

                throw ex;
            }
            
        }

        /// <summary>
        /// Remote Function Module RFC_GET_FUNCTION_INTERFACE.  
        /// 
        /// </summary>
        /// <param name="FUNCNAME">Name of function module</param>
        /// <param name="LANGUAGE">Language for parameter texts</param>
        /// <param name="NONE_UNICODE_LENGTH">Language for parameter texts</param>
        /// <param name="PARAMS">Parameter of function module</param> 
        /// <exception cref="FU_NOT_FOUND"/> 
        /// <exception cref="NAMETAB_FAULT"/>
        [RfcMethod(AbapName = "RFC_GET_FUNCTION_INTERFACE")]
        [SoapDocumentMethodAttribute("http://tempuri.org/RFC_GET_FUNCTION_INTERFACE",
             RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
             RequestElementName = "RFC_GET_FUNCTION_INTERFACE",
             ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
             ResponseElementName = "RFC_GET_FUNCTION_INTERFACE.Response")]
        public virtual void RFC_GET_FUNCTION_INTERFACE(

            [RfcParameter(AbapName = "FUNCNAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
            [XmlElement("FUNCNAME", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string FUNCNAME,
            [RfcParameter(AbapName = "LANGUAGE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
            [XmlElement("LANGUAGE", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string LANGUAGE,
            [RfcParameter(AbapName = "NONE_UNICODE_LENGTH",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
            [XmlElement("NONE_UNICODE_LENGTH", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string NONE_UNICODE_LENGTH,
            [RfcParameter(AbapName = "PARAMS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
            [XmlArray("PARAMS", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            ref RFC_FUNINTTable PARAMS)
        {
            object[] results = null;
            results = this.SAPInvoke("RFC_GET_FUNCTION_INTERFACE", new object[] { FUNCNAME, LANGUAGE, NONE_UNICODE_LENGTH, PARAMS });
            PARAMS = (RFC_FUNINTTable)results[0];

        }


        /// <summary>
        /// Remote Function Module RFC_GET_STRUCTURE_DEFINITION.  
        /// 
        /// </summary>
        /// <param name="TABLENGTH">Length of the table in bytes</param>
        /// <param name="TABNAME">Table name</param>
        /// <param name="UCLEN">Table name</param>
        /// <param name="FIELDS">Field names and features</param> 
        /// <exception cref="TABLE_NOT_ACTIVE"/>
        [RfcMethod(AbapName = "RFC_GET_STRUCTURE_DEFINITION")]
        [SoapDocumentMethodAttribute("http://tempuri.org/RFC_GET_STRUCTURE_DEFINITION",
             RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
             RequestElementName = "RFC_GET_STRUCTURE_DEFINITION",
             ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
             ResponseElementName = "RFC_GET_STRUCTURE_DEFINITION.Response")]
        public virtual void RFC_GET_STRUCTURE_DEFINITION(

            [RfcParameter(AbapName = "TABNAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
            [XmlElement("TABNAME", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string TABNAME,
            [RfcParameter(AbapName = "UCLEN",RfcType=RFCTYPE.RFCTYPE_BYTE, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 1)]
            [XmlElement("UCLEN", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            byte[] UCLEN,
            [RfcParameter(AbapName = "TABLENGTH",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 4)]
            [XmlElement("TABLENGTH", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out int TABLENGTH,
            [RfcParameter(AbapName = "FIELDS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
            [XmlArray("FIELDS", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            ref RFC_FIELDSTable FIELDS)
        {
            object[] results = null;
            results = this.SAPInvoke("RFC_GET_STRUCTURE_DEFINITION", new object[] { TABNAME, UCLEN, FIELDS });
            TABLENGTH = (int)results[0];
            FIELDS = (RFC_FIELDSTable)results[1];

        }

        /// <summary>
        /// Remote Function Module RFC_GET_UNICODE_STRUCTURE.  
        /// 
        /// </summary>
        /// <param name="B1_TABLENGTH"></param>
        /// <param name="B2_TABLENGTH"></param>
        /// <param name="B4_TABLENGTH"></param>
        /// <param name="CHAR_LENGTH"></param>
        /// <param name="UUID"></param>
        /// <param name="ALLOW_HALF_DEEP"></param>
        /// <param name="SKIP_UCS_4_INFO"></param>
        /// <param name="SKIP_UTF16_INFO"></param>
        /// <param name="TABNAME">Table Name</param>
        /// <param name="FIELDS"></param> 
        /// <exception cref="CANNOT_GENERATE1"/> 
        /// <exception cref="CANNOT_GENERATE2"/> 
        /// <exception cref="CANNOT_GENERATE4"/> 
        /// <exception cref="TABLE_NOT_ACTIVE"/> 
        /// <exception cref="UNSUPPORTED_TYPE"/>
        [RfcMethod(AbapName = "RFC_GET_UNICODE_STRUCTURE")]
        [SoapDocumentMethodAttribute("http://tempuri.org/RFC_GET_UNICODE_STRUCTURE",
             RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
             RequestElementName = "RFC_GET_UNICODE_STRUCTURE",
             ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
             ResponseElementName = "RFC_GET_UNICODE_STRUCTURE.Response")]
        public virtual void RFC_GET_UNICODE_STRUCTURE(

            [RfcParameter(AbapName = "ALLOW_HALF_DEEP",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
            [XmlElement("ALLOW_HALF_DEEP", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string ALLOW_HALF_DEEP,
            [RfcParameter(AbapName = "SKIP_UCS_4_INFO",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
            [XmlElement("SKIP_UCS_4_INFO", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string SKIP_UCS_4_INFO,
            [RfcParameter(AbapName = "SKIP_UTF16_INFO",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
            [XmlElement("SKIP_UTF16_INFO", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string SKIP_UTF16_INFO,
            [RfcParameter(AbapName = "TABNAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
            [XmlElement("TABNAME", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string TABNAME,
            [RfcParameter(AbapName = "B1_TABLENGTH",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 4)]
            [XmlElement("B1_TABLENGTH", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out int B1_TABLENGTH,
            [RfcParameter(AbapName = "B2_TABLENGTH",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 4)]
            [XmlElement("B2_TABLENGTH", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out int B2_TABLENGTH,
            [RfcParameter(AbapName = "B4_TABLENGTH",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 4)]
            [XmlElement("B4_TABLENGTH", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out int B4_TABLENGTH,
            [RfcParameter(AbapName = "CHAR_LENGTH",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 4)]
            [XmlElement("CHAR_LENGTH", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out int CHAR_LENGTH,
            [RfcParameter(AbapName = "UUID",RfcType=RFCTYPE.RFCTYPE_BYTE, Optional = true, Direction = RFCINOUT.OUT, Length = 16, Length2 = 16)]
            [XmlElement("UUID", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out byte[] UUID,
            [RfcParameter(AbapName = "FIELDS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
            [XmlArray("FIELDS", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            ref RFC_FLDS_UTable FIELDS)
        {
            object[] results = null;
            results = this.SAPInvoke("RFC_GET_UNICODE_STRUCTURE", new object[] { ALLOW_HALF_DEEP, SKIP_UCS_4_INFO, SKIP_UTF16_INFO, TABNAME, FIELDS });
            B1_TABLENGTH = (int)results[0];
            B2_TABLENGTH = (int)results[1];
            B4_TABLENGTH = (int)results[2];
            CHAR_LENGTH = (int)results[3];
            UUID = (byte[])results[4];
            FIELDS = (RFC_FLDS_UTable)results[5];

        }

        /// <summary>
        /// Remote Function Module RFC_GET_NAMETAB.
        /// </summary>
        /// <param name="HEADER">Table attributes</param>
        /// <param name="TABNAME">Table name</param>
        /// <param name="NAMETAB">Table of the field names and features</param> 
        /// <exception cref="TABLE_NOT_ACTIVE"/>
        [RfcMethod(AbapName = "RFC_GET_NAMETAB")]
        [SoapDocumentMethodAttribute("http://tempuri.org/RFC_GET_NAMETAB",
             RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
             RequestElementName = "RFC_GET_NAMETAB",
             ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
             ResponseElementName = "RFC_GET_NAMETAB.Response")]
        public virtual void RFC_GET_NAMETAB(

            [RfcParameter(AbapName = "TABNAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
            [XmlElement("TABNAME", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            string TABNAME,
            [RfcParameter(AbapName = "HEADER",RfcType=RFCTYPE.RFCTYPE_STRUCTURE, Optional = true, Direction = RFCINOUT.OUT)]
            [XmlElement("HEADER", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            out X030L HEADER,
            [RfcParameter(AbapName = "NAMETAB",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
            [XmlArray("NAMETAB", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            [XmlArrayItem("item", IsNullable=false, Form=XmlSchemaForm.Unqualified)]
            ref X031LTable NAMETAB)
        {
            object[] results = null;
            results = this.SAPInvoke("RFC_GET_NAMETAB", new object[] {
                                                                        TABNAME,NAMETAB });
            HEADER = (X030L)results[0];
            NAMETAB = (X031LTable)results[1];
        }

    } // class
} // namespace
