
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2006-12-21
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace RFCProxyBuilder
{
  /// <summary>
  /// A typed collection of X031L elements.
  /// </summary>
  [Serializable]
  public class X031LTable : SAPTable 
  {
  
    /// <summary>
    /// Returns the element type X031L.
    /// </summary>
    /// <returns>The type X031L.</returns>
    public override Type GetElementType() 
    {
        return (typeof(X031L));
    }

    /// <summary>
    /// Creates an empty new row of type X031L.
    /// </summary>
    /// <returns>The newX031L.</returns>
    public override object CreateNewRow()
    { 
        return new X031L();
    }
     
    /// <summary>
    /// The indexer of the collection.
    /// </summary>
    public X031L this[int index] 
    {
        get 
        {
            return ((X031L)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    /// <summary>
    /// Adds a X031L to the end of the collection.
    /// </summary>
    /// <param name="value">The X031L to be added to the end of the collection.</param>
    /// <returns>The index of the newX031L.</returns>
    public int Add(X031L value) 
    {
        return List.Add(value);
    }
        
    /// <summary>
    /// Inserts a X031L into the collection at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index at which value should be inserted.</param>
    /// <param name="value">The X031L to insert.</param>
    public void Insert(int index, X031L value) 
    {
        List.Insert(index, value);
    }
        
    /// <summary>
    /// Searches for the specified X031L and returnes the zero-based index of the first occurrence in the collection.
    /// </summary>
    /// <param name="value">The X031L to locate in the collection.</param>
    /// <returns>The index of the object found or -1.</returns>
    public int IndexOf(X031L value) 
    {
        return List.IndexOf(value);
    }
        
    /// <summary>
    /// Determines wheter an element is in the collection.
    /// </summary>
    /// <param name="value">The X031L to locate in the collection.</param>
    /// <returns>True if found; else false.</returns>
    public bool Contains(X031L value) 
    {
        return List.Contains(value);
    }
        
    /// <summary>
    /// Removes the first occurrence of the specified X031L from the collection.
    /// </summary>
    /// <param name="value">The X031L to remove from the collection.</param>
    public void Remove(X031L value) 
    {
        List.Remove(value);
    }

    /// <summary>
    /// Copies the contents of the X031LTable to the specified one-dimensional array starting at the specified index in the target array.
    /// </summary>
    /// <param name="array">The one-dimensional destination array.</param>           
    /// <param name="index">The zero-based index in array at which copying begins.</param>           
    public void CopyTo(X031L[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
